### ISSUE TITLE
Easier localization

### ISSUE THREAD

**Issue by PetrToman** [m1x0n/opis-error-presenter#3]
I suggest to move all error messages (strings) into one file per language (in a separate folder), so they can be translated easily. For example:

```
languages
     |
     +--- messages_en.php
     |    $ERROR['Type'] = "The attribute expected to be of type ':expected:' but ':used:' given.";
     |    $ERROR['Constant'] = "The attribute value expected to be ':expected:'.";
     |    ...
     +--- messages_fr.php
     +--- messages_de.php
```

**Comment by m1x0n** [comment]
Hi @PetrToman ! Indeed it sounds like good further improvement. I'm gonna look at it a bit later.

**Comment by m1x0n** [comment]
@PetrToman I managed to implement locale support. You can check it out in https://github.com/m1x0n/opis-error-presenter/releases/tag/v0.4.0
